name: Setup Node.js and dependencies
description: Setup Node.js environment with pnpm dependencies

inputs:
  node-version:
    description: Node.js version
    required: true
  restore-nextjs-cache:
    description: Whether to restore Next.js build cache
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Restore Next.js build output
      if: inputs.restore-nextjs-cache == 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          .next
        key: nextjs-build-${{ inputs.node-version }}-${{ github.sha }}
        fail-on-cache-miss: true
